  FMH[m
  bf-hist-promo[m
* [32mchk-eva[m
  double-ext[m
  eval-cache[m
  killer-no-reduce-lmr[m
  limit_check_extension[m
  master[m
  mdp[m
  multicut-cond-removal[m
  neg-ext[m
  nmp-zugswang-guard[m
  no-prune-ttmove[m
  pawn-corrhist[m
  pawn-corrhist2[m
  probcut[m
  qsearch-no-store[m
  qsearch-tt[m
  qsearch_evasions[m
  tt-fake-mate-pollution[m
  zugswang[m
